SEQ_LEN = 20
THRESHOLD = 0.8
INITIAL_CAPITAL = 10000
MODEL_DIR = "models/"
ALERT_EMAIL = "ALERT_EMAIL"

# Alpaca config
ALPACA_API_KEY = "ALPACA_API_KEY"
ALPACA_SECRET_KEY = "ALPACA_SECRET_KEY"
ALPACA_BASE_URL = "https://paper-api.alpaca.markets"